### PR TITLE
add flag to use gateway code

### PR DESCRIPTION
**Pull request by adkinsjd**
I would like to compile permamote apps without using the gateway code and defining all of the config.h variables. This makes using the gateway library a flag just like using thread.

### CODE REVIEW

**Comment by adkinsjd** [comment]
I expect travis to fail just because master is failing, but I'm happy to patch this up once it is fixed

**Comment by nealjack** [comment]
Thanks!

I have been meaning to mark inclusion for the gateway features with a flag, but haven't gotten around to it. The only thing is that you probably don't want to commit your public key. I have also been meaning to add a `keys` directory within the boards folder to hold the keypair, but have also not gotten around to it.

**Comment by nealjack** [comment]
I just pushed a fix for the mismatched camera function definition - but the build will probably still fail without your inclusion. If you could pull and see if this branch passes with travis, that would be great.

**Comment by adkinsjd** [comment]
I'm going to remove public.c from master - I didn't mean to add it

**Pull request merged**
